# Generated by Django 3.1.7 on 2021-04-04 00:36

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import userprofile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_profiles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=userprofile.models.get_empty_array, size=None)),
                ('liked_profiles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=userprofile.models.get_empty_array, size=None)),
                ('liked_by_profile', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=userprofile.models.get_empty_array, size=None)),
                ('tracks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=userprofile.models.get_empty_array, size=None)),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=userprofile.models.get_empty_features_array, size=None)),
                ('cluster', models.IntegerField(default=-1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
